# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singer_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u6b4c\u624bID')),
                ('singer_name', models.CharField(max_length=100, verbose_name='\u6b4c\u624b\u540d')),
            ],
        ),
    ]
