# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-06 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_items',
            name='music_artist_id',
            field=models.CharField(default=0, max_length=100, verbose_name='\u6b4c\u624bID'),
            preserve_default=False,
        ),
    ]
