# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_items',
            fields=[
                ('music_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u97f3\u4e50ID')),
                ('music_url', models.CharField(max_length=1024, verbose_name='\u6b4c\u66f2 url')),
                ('music_name', models.CharField(max_length=1024, verbose_name='\u6b4c\u66f2\u540d')),
                ('music_album', models.CharField(max_length=1024, verbose_name='\u6b4c\u66f2\u6240\u5c5e\u4e13\u8f91')),
                ('music_mv', models.CharField(max_length=1024, verbose_name='\u6b4c\u66f2 mv')),
                ('music_artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Singer', verbose_name='\u6240\u5c5e\u6b4c\u624b')),
            ],
        ),
        migrations.CreateModel(
            name='Musiccomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=10000, verbose_name='\u8bc4\u8bba\u5185\u5bb9')),
                ('comment_user_id', models.CharField(max_length=100, verbose_name='\u8bc4\u8bba\u7528\u6237 id')),
                ('comment_username', models.CharField(max_length=100, verbose_name='\u8bc4\u8bba\u7528\u6237\u540d')),
                ('comment_like_count', models.CharField(max_length=100, verbose_name='\u8bc4\u8bba\u559c\u6b22\u6570')),
                ('comment_id', models.CharField(max_length=100, verbose_name='\u8bc4\u8bba id')),
                ('music_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Music_items', verbose_name='\u6b4c\u66f2 id')),
            ],
        ),
    ]
