# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-05-09 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_singer_singer_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u7528\u6237id')),
                ('my_list_id', models.CharField(max_length=100, verbose_name='\u6b4c\u5355id')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u88ab\u5173\u6ce8id')),
                ('follow_user_id', models.CharField(max_length=100, verbose_name='\u5173\u6ce8\u8005id')),
            ],
        ),
        migrations.CreateModel(
            name='My_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_list_user_id', models.CharField(max_length=100, verbose_name='\u521b\u5efa\u7528\u6237id')),
                ('my_list_name', models.CharField(max_length=100, verbose_name='\u6b4c\u5355\u540d')),
                ('my_list_count', models.CharField(max_length=100, verbose_name='\u6b4c\u5355\u6b4c\u66f2\u6570')),
                ('my_list_open', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='My_list_to_music',
            fields=[
                ('my_list_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u6b4c\u5355id')),
                ('music_id', models.CharField(max_length=100, verbose_name='\u6b4c\u66f2id')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_user_name', models.CharField(max_length=100, verbose_name='\u7528\u6237\u540d')),
                ('upload_music_name', models.CharField(max_length=100, verbose_name='\u4e0a\u4f20\u6b4c\u66f2\u540d')),
                ('upload_open', models.BooleanField(default=False, verbose_name='\u662f\u5426\u516c\u5f00')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='\u7528\u6237\u540d')),
                ('user_password', models.CharField(max_length=100, verbose_name='\u5bc6\u7801')),
                ('user_nick_name', models.CharField(max_length=100, verbose_name='\u6635\u79f0')),
                ('user_birth', models.CharField(max_length=100, verbose_name='\u751f\u65e5')),
                ('user_sex', models.CharField(max_length=100, verbose_name='\u6027\u522b')),
                ('user_intro', models.CharField(max_length=10024, verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('user_open', models.PositiveIntegerField(default=1, verbose_name='\u662f\u5426\u516c\u5f00\u4e2a\u4eba\u4fe1\u606f(\u7c89\u4e1d\uff0c\u6240\u6709\u4eba\uff0c\u4fdd\u5bc6)(0,1,-1)')),
                ('user_list_open', models.BooleanField(default=True, verbose_name='\u662f\u5426\u516c\u5f00\u6536\u85cf\u4fe1\u606f')),
            ],
        ),
    ]
